version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - backend-settings:/app/Settings
      - frontend-settings:/app/wwwroot/client-settings
      - files:/app/AppFiles
    depends_on:
      - db
      - elastic

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: StrongPassword1234!

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
    depends_on:
      - elastic

volumes:
  mongo_data:
  es-data01:
    driver: local
  backend-settings:
  frontend-settings:
  files: